services:
  build_meet:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/host_dist
    command: sh -c "cp -a /app/dist/. /host_dist/ && echo 'Build successful. Files extracted to local ./dist directory.' && ls -la /host_dist"
